version: '3'
services:
  helmfile:
    build:
      context: .
    image: chatwork/helmfile
  sut:
    image: kiwicom/dgoss
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
    command: /usr/local/bin/dgoss run --entrypoint tail chatwork/helmfile -f /dev/null
    container_name: helmfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - helmfile
