version: '3'
services:
  fpm:
    build:
      context: .
    image: chatwork/php-fpm
  sut:
    image: kiwicom/dgoss
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
    command: /usr/local/bin/dgoss run chatwork/php-fpm
    volumes:
      - ./goss/goss.yaml:/goss/goss.yaml
      - /var/run/docker.sock:/var/run/docker.sock
