version: '3'
services:
  docker-fluentd:
    build:
      context: .
    image: chatwork/docker-fluentd
  sut:
    image: kiwicom/dgoss
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
    command: /usr/local/bin/dgoss run --entrypoint tail chatwork/docker-fluentd -f /dev/null
    container_name: docker-fluentd
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - docker-fluentd
