version: '3'
services:
  openjdk11-sbt:
    build:
      context: .
    image: chatwork/openjdk11-sbt
  sut:
    image: kiwicom/dgoss
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
    command: /usr/local/bin/dgoss run --entrypoint '' chatwork/openjdk11-sbt tail -f /dev/null
    container_name: openjdk11-sbt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - openjdk11-sbt
