version: '3'
services:
  openjdk8:
    build:
      context: .
    image: chatwork/openjdk8
  sut:
    image: kiwicom/dgoss
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
    command: /usr/local/bin/dgoss run --entrypoint '' chatwork/openjdk8 tail -f /dev/null
    container_name: openjdk8
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - openjdk8
