version: 2.1
jobs:
  test:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run: make ci:diff
      - run: make ci:diff | xargs -I{} /bin/bash -c "cd ./{} && make build || exit 255"
      - run: make ci:diff | xargs -I{} /bin/bash -c "cd ./{} && make test || exit 255"
  push:
    machine: true
    steps:
      - checkout
      - run: docker login -u="${DOCKER_REGISTRY_USERNAME}" -p="${DOCKER_REGISTRY_PASSWORD}"
      - run: make ci:diff
      - run: make ci:diff | xargs -I{} /bin/bash -c "cd ./{} && make build || exit 255"
      - run: make ci:diff | xargs -I{} /bin/bash -c "cd ./{} && make push || exit 255"
      - run:
          name: notification failed
          command: |
            make ci:diff | xargs -I{} /bin/bash -c '
              version=$(docker inspect -f "{{.Config.Labels.version}}" chatwork/{});
              if [ "$(docker inspect --format="{{json .RepoDigests}}" chatwork/{}:${version})" != "[]" ]; then
                changelog=$(make ci:changelog -e DIR="{}/");
                make ci:notify -e TITLE="Release chatwork/{}:${version} (gogo)" \
                               -e BODY="$(echo -e "changelog\n${changelog}")";
              else
                make ci:notify -e TITLE="CircleCI: Failed push chatwork/{}:${version} (devil)" \
                               -e BODY="$(git log -1 --pretty=format:"%h - %an : %s" ${CIRCLE_BRANCH})";
              fi
            '
          when: on_fail
      - run:
          name: notification success
          command: |
            make ci:diff | xargs -I{} /bin/bash -c '
              version=$(docker inspect -f {{.Config.Labels.version}} chatwork/{});
              changelog=$(make ci:changelog -e DIR="{}/");
              make ci:notify -e TITLE="Release chatwork/{}:${version} (gogo)" \
                             -e BODY="$(echo -e "changelog\n${changelog}")";
            '
          when: on_success
  mod:
    machine: true
    steps:
      - checkout
      - run:
          name: Install mod
          command: |
            curl -sSL https://github.com/variantdev/mod/releases/download/v0.6.1/mod_0.6.1_linux_amd64.tar.gz | tar zx -C /tmp
            sudo mv /tmp/mod /usr/local/bin/mod
            sudo chmod 755 /usr/local/bin/mod
      - run:
          name: Update dependencies
          command: |
            git config --global user.email "server_admin+cw-circleci@chatwork.com"
            git config --global user.name "CircleCI"
            ls */variant.mod | xargs -I{} dirname {} | xargs -I{} /bin/bash -c '
              echo "\n# {}"
              git checkout master
              git reset --hard master
              cd {} && mod up --build --branch 'mod-up-{}' --pull-request --title "[{}] update dependencies"
            '
  merge:
    machine: true
    steps:
      - checkout
      - run:
          name: Install PR CLI
          command: |
            curl -sSL https://github.com/k-kinzal/pr/releases/download/v0.2.0/pr_darwin_amd64.tar.gz | tar zx -C /tmp
            sudo mv /tmp/pr /usr/local/bin/prcli
            sudo chmod 755 /usr/local/bin/prcli
      - run:
          name: Auto merge (DRY RUN)
          command: |
            prcli --no-exit-code validate $CIRCLE_PR_USERNAME/$CIRCLE_PR_REPONAME --with-statuses --with-checks \
              -l 'state == `"open"`' \
              -l 'base.ref == `"master"`' \
              -l 'starts_with(head.ref, `"mod-up-"`)' \
              -l 'user.login == `"cw-circleci"`' \
              -l 'length(statuses[?context == `"ci/circleci: test"` && state == `"success"`]) == `1`' 2>stderr
      - run:
          name: Auto merge
          command: |
            prcli merge $CIRCLE_PR_USERNAME/$CIRCLE_PR_REPONAME --with-statuses --with-checks \
              -l 'state == `"open"`' \
              -l 'base.ref == `"master"`' \
              -l 'starts_with(head.ref, `"mod-up-"`)' \
              -l 'user.login == `"cw-circleci"`' \
              -l 'length(statuses[?context == `"ci/circleci: test"` && state == `"success"`]) == `1`'
      - run:
          name: Notification failed
          command: |
              make ci:notify -e TITLE="CircleCI: Failed auto merge (devil)" \
                             -e BODY="$(cat stderr)"
          when: on_fail
workflows:
  version: 2
  integration:
    jobs:
      - test
      - push:
          requires:
            - test
          filters:
            branches:
              only: master
  update_dependecies:
    jobs:
      - mod
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
  auto_merge:
    jobs:
      - merge
    triggers:
      - schedule:
          cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"
          filters:
            branches:
              only:
                - master
