version: 2.1
jobs:
  test:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run: make ci:diff
      - run: make ci:diff | xargs -I{} /bin/bash -c "cd ./{} && make build || exit 255"
      - run: make ci:diff | xargs -I{} /bin/bash -c "cd ./{} && make test || exit 255"
  push:
    machine: true
    steps:
      - checkout
      - run: docker login -u="${DOCKER_REGISTRY_USERNAME}" -p="${DOCKER_REGISTRY_PASSWORD}"
      - run: make ci:diff
      - run: make ci:diff | xargs -I{} /bin/bash -c "cd ./{} && make build || exit 255"
      - run: make ci:diff | xargs -I{} /bin/bash -c "cd ./{} && make push || exit 255"
      - run:
          name: notification failed
          command: |
            make ci:diff | xargs -I{} /bin/bash -c '
              version=$(docker inspect -f "{{.Config.Labels.version}}" chatwork/{});
              if [ "$(docker inspect --format="{{json .RepoDigests}}" chatwork/{}:${version})" != "[]" ]; then
                changelog=$(make ci:changelog -e DIR="{}/");
                make ci:notify -e TITLE="Release chatwork/{}:${version} (gogo)" \
                               -e BODY="$(echo -e "changelog\n${changelog}")";
              else
                make ci:notify -e TITLE="CircleCI: Failed push chatwork/{}:${version} (devil)" \
                               -e BODY="$(git log -1 --pretty=format:"%h - %an : %s" ${CIRCLE_BRANCH})";
              fi
            '
          when: on_fail
      - run:
          name: notification success
          command: |
            make ci:diff | xargs -I{} /bin/bash -c '
              version=$(docker inspect -f {{.Config.Labels.version}} chatwork/{});
              changelog=$(make ci:changelog -e DIR="{}/");
              make ci:notify -e TITLE="Release chatwork/{}:${version} (gogo)" \
                             -e BODY="$(echo -e "changelog\n${changelog}")";
            '
          when: on_success
  mod:
    machine: true
    steps:
      - checkout
      - run:
          name: Install mod
          command: |
            curl -sSL https://github.com/variantdev/mod/releases/download/v0.6.1/mod_0.6.1_linux_amd64.tar.gz | tar zx -C /tmp
            sudo mv /tmp/mod /usr/local/bin/mod
            sudo chmod 755 /usr/local/bin/mod
      - run:
          name: Update dependencies
          command: |
            ls */variant.mod | xargs -I{} dirname {} | xargs -I{} /bin/bash -c '
              git checkout master
              git reset --hard master
              cd {} && mod up --build --branch 'mod-up-{}' --pull-request --title "[{}] update dependencies"
            '
workflows:
  version: 2
  integration:
    jobs:
      - test
      - push:
          requires:
            - test
          filters:
            branches:
              only: master
  update_dependecies:
    jobs:
      - mod
    triggers:
      - schedule:
          cron: "6 * * * *"
          filters:
            branches:
              only:
                - master
