version: '3'
services:
  jq:
    build:
      context: .
    image: chatwork/jq
  sut:
    image: kiwicom/dgoss
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
    command: /usr/local/bin/dgoss run --entrypoint '' chatwork/jq tail -f /dev/null
    container_name: jq
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - jq
