version: '3'
services:
  datadog-agent-with-network:
    build:
      context: .
    image: chatwork/datadog-agent-with-network
  sut:
    image: kiwicom/dgoss
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
    command: /usr/local/bin/dgoss run chatwork/datadog-agent-with-network
    container_name: datadog-agent-with-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - datadog-agent-with-network
