version: '3'
services:
  protobuf:
    build:
      context: .
    image: chatwork/protobuf
  sut:
    image: kiwicom/dgoss
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
    command: /usr/local/bin/dgoss run --entrypoint '' chatwork/protobuf tail -f /dev/null
    container_name: protobuf
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - protobuf
