version: '3'
services:
  gatling-ecs-client:
    build:
      context: .
    image: chatwork/gatling-ecs-client
  sut:
    image: kiwicom/dgoss
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
    command: /usr/local/bin/dgoss run --entrypoint tail chatwork/gatling-ecs-client tail -f /dev/null
    container_name: gatling-ecs-client
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - gatling-ecs-client
