version: '3'
services:
  docker-dd-agent-no-checks:
    build:
      context: .
    image: chatwork/docker-dd-agent-no-checks
  sut:
    image: kiwicom/dgoss
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
    command: /usr/local/bin/dgoss run --entrypoint tail chatwork/docker-dd-agent-no-checks -f /dev/null
    container_name: docker-dd-agent-no-checks
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - docker-dd-agent-no-checks
