version: '3'
services:
  eksctl:
    build:
      context: .
    image: chatwork/eksctl
  sut:
    image: kiwicom/dgoss
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
    command: /usr/local/bin/dgoss run --entrypoint tail chatwork/eksctl -f /dev/null
    container_name: eksctl
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - eksctl
