version: '3'
services:
  busybox:
    build:
      context: .
    image: chatwork/argocd-helmfile
  sut:
    image: kiwicom/dgoss
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
    command: /usr/local/bin/dgoss run --entrypoint '' chatwork/argocd-helmfile tail -f /dev/null
    container_name: argocd-helmfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
