version: '3'
services:
  kafka-connect-mysql:
    build:
      context: .
    image: chatwork/kafka-connect-mysql
  sut:
    image: kiwicom/dgoss
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
    command: /usr/local/bin/dgoss run --entrypoint '' chatwork/kafka-connect-mysql tail -f /dev/null
    container_name: kafka-connect-mysql
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - kafka-connect-mysql
