version: '3'
services:
  sut:
    image: kiwicom/dgoss
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
    command: /usr/local/bin/dgoss run chatwork/mailcatcher
    container_name: mailcatcher
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
