version: '3'
services:
  busybox:
    build:
      context: .
    image: chatwork/kube-fluentd-operator
  sut:
    image: kiwicom/dgoss
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
    command: /usr/local/bin/dgoss run --entrypoint tail chatwork/kube-fluentd-operator -f /dev/null
    volumes:
      - ./goss/goss.yaml:/goss/goss.yaml
      - /var/run/docker.sock:/var/run/docker.sock
