version: '3'
services:
  kube-fluentd-operator:
    build:
      context: .
    image: chatwork/kube-fluentd-operator
  sut:
    image: kiwicom/dgoss
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
    command: /usr/local/bin/dgoss run --entrypoint tail chatwork/kube-fluentd-operator -f /dev/null
    container_name: kube-fluentd-operator
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - kube-fluentd-operator
