file:
  /bin/helm:
    exists: true
    mode: "0755"
  /bin/helmfile:
    exists: true
    mode: "0755"
command:
  /bin/helm plugin list:
    exit-status: 0
    stdout:
      - /^diff/
      - /^secrets/
  /bin/helmfile -v:
    exit-status: 0
    stdout:
      - v0.23.1
