version: '3'
services:
  jq:
    build:
      context: .
    image: chatwork/gratan
  sut:
    image: kiwicom/dgoss
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
    command: /usr/local/bin/dgoss run --entrypoint '' chatwork/gratan tail -f /dev/null
    container_name: gratan
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - gratan
