version: '3'
services:
  kube-schedule-scaler:
    build:
      context: .
    image: chatwork/kube-schedule-scaler
  sut:
    image: kiwicom/dgoss
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
    command: /usr/local/bin/dgoss run --entrypoint '' chatwork/kube-schedule-scaler tail -f /dev/null
    container_name: kube-schedule-scaler
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - kube-schedule-scaler
