version: '3'
services:
  kumina-postfix-exporter:
    build:
      context: .
    image: chatwork/kumina-postfix-exporter
  sut:
    image: kiwicom/dgoss
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
    command: /usr/local/bin/dgoss run --entrypoint '' chatwork/kumina-postfix-exporter tail -f /dev/null
    container_name: kumina-postfix-exporter
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - kumina-postfix-exporter
