version: '3'
services:
  busybox:
    build:
      context: .
    image: chatwork/newrelic-php-agent
  sut:
    image: kiwicom/dgoss
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
    command: /usr/local/bin/dgoss run --entrypoint '' chatwork/newrelic-php-agent tail -f /dev/null
    container_name: newrelic-php-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock