command:
  /usr/local/bin/argocd version:
    exit-status: 1
    stdout:
    - v0.12.3
  /usr/local/bin/kubectl version:
    exit-status: 1
    stdout:
    - v1.14.0
  /usr/local/bin/helm version:
    exit-status: 1
    stdout:
    - v2.12.1
  /usr/local/bin/helm plugin list:
    exit-status: 0
    stdout:
      - /^diff/
      - /^import/
      - /^secrets/
      - /^tiller/
  /bin/helmfile -v:
    exit-status: 0
    stdout:
      - v0.45.3
