name: kubectl update dependencies
on:
  schedule:
  - cron: '2 */1 * * *'

jobs:
  up:
    name: mod up
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: variantdev/mod-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MOD_ACTION_WORKING_DIR: kubectl/
      with:
        args: up --build --pull-request --title "[kubectl] update dependencies"
